### ISSUE TITLE
Duda sobre fecha de un fallo 

### ISSUE THREAD

**Issue by Arejula11** [sistemas-de-informacion/docs#358]
He investigado sobre el caso de Nestle y SAP. He encontrado el siguiente articulo : [Nestlé’S ERP Implementation “Open Case”](https://medium.com/@ERP_Myanmar/nestl%C3%A9s-erp-implementation-open-case-b05c469c0e3c). En fracasar-con-erp.md se encuentra otro articulo sobre este suceso  en los 2000. Mi articulo menciona que la implementación del ERP comenzó en 1997 y no fue hasta 2003 cuando se completó su implementación. Bien es cierto que el gran desastre ocurrió en el 2000, pero el proyecto de incluir SAP comenzó antes.

Mi pregunta es si lo colocó en 1997 o en el 2000 junto al otro articulo.

**Comment by fjlopez** [comment]
2000 sería lo más apropiado.

**Comment by Arejula11** [comment]
Revisando los enlaces, me he dado cuenta que el link que había encontrado ya se encuentra en el documento. Sin embargo, se habla del mismo caso en dos secciones distintas. En la sección de 1997 y en la sección 2000. 

¿Corrijo esta falta de coherencia o busco otro link?
